version : "3.3"
services:
  database:
    image: mysql:8.0.30
    restart: always
    container_name: database
    environment:
      MYSQL_DATABASE: bogeo
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3304:3306"
    networks:
      - springboot-mysql-net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    container_name: bogeo_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3304/bogeo?useSSL=false&serverTimezone=Asia/Seoul&character_set_server=utf8mb4&validationQuery="select 1"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - springboot-mysql-net
networks:
  springboot-mysql-net:
    driver: bridge